name = "MutableConvexHulls"
uuid = "948c7aac-0e5e-4631-af23-7a6bb7a17825"
version = "0.4.0"
authors = ["Tom McGrath <tmcgrath325@gmail.com> and contributors"]

[deps]
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
PairedLinkedLists = "7a42b37b-ed3b-477a-9848-3661f53bb718"

[compat]
Aqua = "0.8"
DoubleFloats = "1.4"
ExplicitImports = "1.15"
OffsetArrays = "1"
PairedLinkedLists = "0.3"
Random = "1"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "Aqua", "ExplicitImports", "OffsetArrays"]
