name = "MutableConvexHulls"
uuid = "948c7aac-0e5e-4631-af23-7a6bb7a17825"
authors = ["Tom McGrath <tmcgrath325@gmail.com> and contributors"]
version = "0.1.0"

[deps]
PairedLinkedLists = "7a42b37b-ed3b-477a-9848-3661f53bb718"

[compat]
julia = "1.6"
PairedLinkedLists = "0.2"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
